### ISSUE TITLE
Build a separate package @pxblue/types to hold PXBlueColor types

### ISSUE THREAD

**Issue by huayunh** [pxblue/colors#16]
#### Describe the desired behavior
We should be able to include `import { PXBLueColor } from @pxblue/types` to define the `PXBlueColor` type.

#### Describe the current behavior
Right now, type `PXBlueColor` is copied and pasted in both `ui/palette.ts` and `branding/palette.ts`.

#### Is this request related to a current issue?
NO

**Comment by emclaug2** [comment]
@pxblue/types has been published on npm and integrated into @pxblue/colors & @pxblue/colors-branding.
