### ISSUE TITLE
White 100 shall be changed to #FBFBFB

### ISSUE THREAD

**Issue by huayunh** [pxblue/colors#24]
#### Describe the desired behavior

White100 shall be `#FBFBFB`.

In React theme, the table color is currently set using string literal — should replace that once we publish this change here.

#### Describe the current behavior

The current color, `#FDFDFD`, is too bright to show an alternating color in table rows. 

#### Additional Context
From the discussion of a properly designed PXB table:
![image](https://user-images.githubusercontent.com/8997218/113195262-11398580-9230-11eb-8964-b8557723be71.png)

The change has been made in DSM.

**Comment by joebochill** [comment]
Either fix the Angular and React themes to use this color after the update, or log new issues in those repos to update them later.
